### ISSUE TITLE
ERROR - string indices must be integers, not str

### ISSUE THREAD

**Issue by emakhankov** [vaclavcadek/keras2pmml#12] opened 2020-05-17 10:53 UTC
I am making a simple network and when I try to convert, I get an error TypeError: string indices must be integers, not str
On the line of code
`layer_activations = map (lambda x: x ['config'] ['activation'], estimator.get_config ())`
in the package
/usr/local/lib/python2.7/dist-packages/keras2pmml/__init__.pyc

I looked at it because the method get_config () of the Keras model returns a dictionary at the first level of which there is no «config» key

The names of activation functions can be read like this
```
lst = model2.get_config ()
for x in lst ['layers']:
   print (x ['config'] ['activation'])
```

or replace the line with this one
`layer_activations = map (lambda x: x ['config'] ['activation'], estimator.get_config () ['layers'])`

-----------

my source code with generating an error
I even made the downgrade in my colab notebook
```

!pip install tensorflow==1.9.0
!pip install Keras==2.2.4
!pip install Keras-Applications==1.0.6
!pip install Keras-Preprocessing==1.0.5
!pip install keras2pmml==0.1.0


from keras2pmml import keras2pmml
params = {
    'feature_names': ['sepal_length', 'sepal_width', 'petal_length', 'petal_width'],
    'target_values': ['setosa', 'virginica', 'versicolor'],
    'target_name': 'specie',
    'copyright': 'Evgeny Makhankov',
    'description': 'Simple Keras model for Iris dataset.',
    'model_name': 'Iris Model'
}

from keras.models import Sequential
from keras.layers.core import Dense


from keras.utils import np_utils

std = StandardScaler()
X_train_scaled = std.fit_transform(x_train)
X_test_scaled = std.transform(x_test)

y_train_ohe = np_utils.to_categorical(y_train)
y_test_ohe = np_utils.to_categorical(y_test)


model2 = Sequential()
model2.add(Dense(8, input_dim=4, activation='tanh'))
model2.add(Dense(8, input_dim = 8, activation='tanh'))
model2.add(Dense(3, activation='softmax'))

model2.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
model2.fit(x_train, y_train_ohe, epochs=10, batch_size=1, verbose=1,
          validation_data=(x_test, y_test_ohe))

keras2pmml(estimator=model2, transformer=std,  file='keras_iris.pmml', **params)
```

and I got 
```

/usr/local/lib/python2.7/dist-packages/keras2pmml/__init__.pyc in <lambda>(x)
    144     layer_weights = estimator.get_weights()[0::2]
    145     layer_biases = estimator.get_weights()[1::2]
--> 146     layer_activations = map(lambda x: x['config']['activation'], estimator.get_config())
    147     for layer, params in enumerate(zip(layer_weights, layer_biases, layer_activations)):
    148         weights = params[0].astype(str)

TypeError: string indices must be integers, not str
```

**Comment by vaclavcadek** [comment] 2020-05-17 17:27
Hi,

Seems like a duplicate issue - see #10  for details. This is due to the fact that Keras changed the API between version 1 and 2. When I was writing this library there was only Keras 1.* thus the latest published version of this keras2pmml on PyPi doesn't contain changes to reflect that.

Easy fix seems to be using version straight from Github as follows:
`pip install git+https://github.com/vaclavcadek/keras2pmml`

(It might also not work even after that as it seems you are using Python2.)

Hope it helps,
Vaclav

**Comment by emakhankov** [comment] 2020-05-18 07:30
Thanks, it is working now

**Comment by vaclavcadek** [comment] 2020-05-18 08:34
Closing now as duplicate of #10. There is a workaround to install keras2pmml straight from Github. Publishing new release would be very welcomed.

**Closed by vaclavcadek** 2020-05-18 08:34 UTC
